name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - gh-pages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run tests
        run: npm test

      - name: Build 
        run: npm run build

      - name: Deploy latest
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          destination_dir: latest

      - name: Extract path
        shell: bash
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy PR
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          destination_dir: ${{ steps.extract_branch.outputs.branch }}

      - name: Comment PR
        uses: harupy/comment-on-pr@master
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: comment-link.md